version: 0.2
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - frp build --production --config=frp.config.js
artifacts:
  files:
    - '**/*'
  base-directory: wp
cache:
  paths:
    - node_modules/**/*
